@echo off
echo Starting PaperLessGov Project...

echo.
echo [1/3] Setting up Backend...
cd backend
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing backend requirements...
pip install -r requirements.txt
echo Running migrations...
python manage.py migrate
echo Resetting demo users...
python reset_users.py
echo Unlocking any locked accounts...
python manage.py axes_reset
echo Starting Backend Server...
start "Backend Server" cmd /k "venv\Scripts\activate.bat && python manage.py runserver 0.0.0.0:8000"

echo.
echo [2/3] Setting up Frontend...
cd ..\frontend
echo Installing frontend dependencies...
call npm install
echo Starting Frontend Server...
start "Frontend Server" cmd /k "npm start"

echo.
echo [3/3] Done! The project should open in your browser shortly.
echo If login fails, please check the console for errors.
pause
