# Generated by Django 6.0.4 on 2026-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprediction',
            name='detected_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='current_stage',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Escalated', 'Escalated'), ('Returned for Correction', 'Returned for Correction')], default='Uploaded', max_length=50),
        ),
    ]
