# Generated by Django 6.0.3 on 2026-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Clerk', 'Clerk'), ('Officer', 'Officer'), ('Higher Authority', 'Higher Authority'), ('Citizen', 'Citizen')], default='Clerk', max_length=20),
        ),
    ]
