# Generated by Django 6.0.3 on 2026-05-04 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_file_citizen_email_file_citizen_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Clerk', 'Clerk'), ('Officer', 'Officer'), ('Higher Authority', 'Higher Authority'), ('Head', 'Head'), ('Admin', 'Admin'), ('Citizen', 'Citizen')], default='Clerk', max_length=20),
        ),
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(max_length=100)),
                ('target_department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded to Officer'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('confidentiality', models.CharField(choices=[('Simple', 'Simple'), ('Confidential', 'Confidential')], default='Simple', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.file')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
