# Generated by Django 6.0.3 on 2026-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filerequest_subject_alter_filerequest_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprediction',
            name='decision',
            field=models.CharField(default='ESCALATE', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='flags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='key_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded to Officer'), ('Escalated', 'Escalated to State Govt'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
