# Generated by Django 6.0.3 on 2026-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aiprediction_decision_aiprediction_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
